# Минимальные настройки для ClickHouse
replicaCount: 3
persistence:
  enabled: true
  size: 10Gi
resources:
  requests:
    cpu: 500m
    memory: 1Gi
auth:
  enabled: false  # Отключаем аутентификацию для упрощения