apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-master
  namespace: clickhouse
spec:
  serviceName: postgresql-master
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-master
  template:
    metadata:
      labels:
        app: postgresql-master
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret"
            - name: POSTGRES_DB
              value: "app_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          command:
            - bash
            - -c
            - |
              echo "wal_level = replica" >> /var/lib/postgresql/data/postgresql.conf
              echo "max_wal_senders = 5" >> /var/lib/postgresql/data/postgresql.conf
              echo "hot_standby = on" >> /var/lib/postgresql/data/postgresql.conf
              exec docker-entrypoint.sh postgres
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi