apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-replica
  namespace: clickhouse
spec:
  serviceName: postgresql-replica
  replicas: 2
  selector:
    matchLabels:
      app: postgresql-replica
  template:
    metadata:
      labels:
        app: postgresql-replica
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          env:
            - name: PRIMARY_HOST
              value: "postgresql-master"
          command:
            - bash
            - -c
            - |
              rm -rf /var/lib/postgresql/data/*
              PGPASSWORD=secret pg_basebackup -h ${PRIMARY_HOST} -U admin -D /var/lib/postgresql/data -P -R
              echo "hot_standby = on" >> /var/lib/postgresql/data/postgresql.conf
              touch /var/lib/postgresql/data/standby.signal
              exec docker-entrypoint.sh postgres
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi