server:
  port: 8082
spring:
  application:
    name: sui-api
  datasource:
    url: jdbc:postgresql://postgresql-ha-postgresql-headless.sui-indexer.svc.cluster.local:5432/appdb?loadBalanceHosts=true&targetServerType=preferSecondary
    username: postgres
    password: postgres123
    hikari:
      connection-init-sql: "SET TRANSACTION READ ONLY"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#springdoc:
#  api-docs:
#    path: /v3/api-docs/flight-aggregator
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
logging:
  level:
    org.springframework.kafka: error
