server:
  port: 8082
spring:
  application:
    name: sui-api
  datasource:
    url: jdbc:postgresql://localhost:54321/suiindex
    username: postgres
    password: postgres3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  clickhouse:
    datasource:
      jdbc-url: jdbc:clickhouse://localhost:8123/suiaggr
      username: suiuser
      password: "suipass"
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
#springdoc:
#  api-docs:
#    path: /v3/api-docs/flight-aggregator
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
logging:
  level:
    org.springframework.kafka: error
