apiVersion: v1
kind: Service
metadata:
  name: indexing-service
  namespace: sui-indexer
spec:
  clusterIP: None
  selector:
    app: indexing-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexing-service
  namespace: sui-indexer
spec:
  serviceName: indexing-service
  replicas: 3
  selector:
    matchLabels:
      app: indexing-service
  template:
    metadata:
      labels:
        app: indexing-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: indexing-service
          image: dordidora/indexing-service
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
