apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse-cluster
  namespace: sui-indexer
spec:
  configuration:
    clusters:
      - name: "sui-cluster"
        layout:
          shardsCount: 1
          replicasCount: 3
#        zookeeper:
#          nodes:
#            - host: zookeeper-0.zookeeper.clickhouse.svc.cluster.local
#              port: 2181
#            - host: zookeeper-1.zookeeper.clickhouse.svc.cluster.local
#              port: 2181
  templates:
    podTemplates:
      - name: clickhouse-pod
        metadata:
          labels:
            custom.label: "label.backend-db"
          spec:
            containers:
              - name: clickhouse
                image: yandex/clickhouse-server:21.8
                resources:
                  requests:
                    cpu: "1000m"
          serviceTemplates:
            - name: svc-template
              generateName: chendpoint-{chi}
              metadata:
                labels:
                  custom.label: "custom.test"
                annotations:
                  service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
              spec:
                ports:
                  - name: http
                    port: 8123
                  - name: tcp
                    port: 9000
                type: LoadBalancer
          volumeClaimTemplates:
            - name: data-volume
              spec:
                storageClassName: gp2
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi